### ISSUE TITLE
Allow room-type calculate room price by different ways

### ISSUE THREAD

**Issue by anhskohbo** [awethemes/awebooking#58]
For now, awebooking only calculate room price by: `night * base-price` 

As the explain at [here]( https://academy.hotellinkage.com/different-pricing-models-in-the-hotel-industry-per-room-occupancy-based-and-per-person-pricing-1f514705a5e3), they say have three common type of calculate cost and call that is "Pricing Models".

- Per room (currently)
- Occupancy-based pricing
- Per person pricing

**Comment by TadeasKula** [comment]
The issue is, we have a night * person based pricing.

We have a starting price for one apartment. That is 1470 CZK

And now we have three tariffs - adult, senior and child
Adult for 490 CZK, senior for 390 CZK and child for 390 CZK

What we need is the calculator to work like this:
If I have for example 2 adults, show 1470 CZK, because it is less then the starting price for the apartment.
But if I have for example 2 adults and 2 children, show 1760, because the sum is higher than the starting price.

Thats the whole thing.
